---
- name: Pull Docker Image and Create the Container
  hosts: all
  tasks:
    - name: Docker login
      shell:
        cmd: docker login
    - name: Pulling the Image
      shell:
        cmd: docker pull mohit24lkt/devopscalc:latest
